# Generated by Django 5.2.17 on 2026-09-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True,
                help_text="ID чата в Telegram для получения уведомлений",
                max_length=100,
                null=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_telegram_verified",
            field=models.BooleanField(
                default=False, verbose_name="Telegram верифицирован"
            ),
        ),
    ]
