# Generated by Django 5.2.17 on 2026-09-01 11:28

import django.db.models.deletion
import habits.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место", max_length=255, verbose_name="Место"
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Укажите дату", verbose_name="Дата"),
                ),
                (
                    "time",
                    models.TimeField(help_text="Укажите время", verbose_name="Время"),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие",
                        max_length=500,
                        verbose_name="Действие, которое нужно выполнить",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите признак приятной привычки",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки в днях (от 1 до 7 дней)",
                        validators=[habits.validators.validate_periodicity_range],
                        verbose_name="Периодичность (дни)",
                    ),
                ),
                (
                    "prize",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=500,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки (10-120 секунд)",
                        validators=[habits.validators.validate_time_to_complete_range],
                        verbose_name="Время на выполнение (секунды)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если хотите опубликовать привычку в общий доступ",
                        verbose_name="Признак публичности",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connected_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите создателя привычки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("connected_habit__isnull", False),
                            ("prize__isnull", False),
                            _negated=True,
                        ),
                        name="no_both_prize_and_connected_habit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_pleasant", True),
                            ("prize__isnull", False),
                            _negated=True,
                        ),
                        name="pleasant_no_prize",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("connected_habit__isnull", False),
                            ("is_pleasant", True),
                            _negated=True,
                        ),
                        name="pleasant_no_connected_habit",
                    ),
                ],
            },
        ),
    ]
