# Generated by Django 5.2.17 on 2026-09-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="date",
            field=models.DateField(
                blank=True, help_text="Укажите дату", null=True, verbose_name="Дата"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True, help_text="Укажите время", null=True, verbose_name="Время"
            ),
        ),
    ]
