# Generated by Django 5.2.17 on 2026-09-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_date_alter_habit_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
